## Dockerfile for dev
## Differs from the release Dockerfile in that it allows re-compiling and re-starting
## the webserver from within the container

ARG GO_VERSION
FROM golang:$GO_VERSION

# we use runit so that we can stop the service without killing the container, and consequently
# play around with it
RUN apt-get update && apt-get install --yes runit
RUN mkdir /etc/service/webhook \
    && /bin/bash -c "echo -e '"'#!/bin/bash\nexec /go/src/github.com/wk8/k8s-gmsa-admission-webhook/k8s-gmsa-admission-webhook 2>&1\n'"' > /etc/service/webhook/run" \
    && chmod +x /etc/service/webhook/run
RUN ln -s /usr/bin/sv /etc/init.d/webhook

WORKDIR /go/src/github.com/wk8/k8s-gmsa-admission-webhook

# install go dependencies
RUN curl https://glide.sh/get | sh
COPY glide.* ./
RUN glide install -v

# build
COPY *.go ./
RUN go build

# copy the rest
COPY . .

CMD ["runsvdir", "/etc/service"]
