# an RBAC role to grant `use` access to some credspecs

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .ClusterRoleName }}
rules:
- apiGroups: ["windows.k8s.io"]
  resources: ["gmsacredentialspecs"]
  verbs: ["use"]
  resourceNames:
{{- range $_, $csn := .CredSpecNames }}
    - {{ $csn }}
{{- end }}
