# a sample cred spec

apiVersion: windows.k8s.io/v1alpha1
kind: GMSACredentialSpec
metadata:
  name: {{ index .CredSpecNames 2 }}
credspec:
  ActiveDirectoryConfig:
    GroupManagedServiceAccounts:
    - Name: WebApplication2
      Scope: CONTOSO
    - Name: WebApplication2
      Scope: contoso.com
  CmsPlugins:
  - ActiveDirectory
  DomainJoinConfig:
    DnsName: contoso.com
    DnsTreeName: contoso.com
    Guid: 244818ae-87ca-4fcd-92ec-e79e5252348a
    MachineAccountName: WebApplication2
    NetBiosName: CONTOSO
    Sid: S-1-5-21-2126729477-2524275714-3294792973
