## a simple deployment with a pod-level GMSA *content* annotation already set

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ .TestName }}
  name: {{ .TestName }}
  namespace: {{ .Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .TestName }}
  template:
    metadata:
      labels:
        app: {{ .TestName }}
      annotations:
        pod.alpha.windows.kubernetes.io/gmsa-credential-spec-name: {{ index .CredSpecNames 0 }}
        pod.alpha.windows.kubernetes.io/gmsa-credential-spec: "{\"ActiveDirectoryConfig\":{\"GroupManagedServiceAccounts\":[{\"Name\":\"WebApplication0\",\"Scope\":\"CONTOSO\"},{\"Name\":\"WebApplication0\",\"Scope\":\"contoso.com\"}]},\"CmsPlugins\":[\"ActiveDirectory\"],\"DomainJoinConfig\":{\"DnsName\":\"contoso.com\",\"DnsTreeName\":\"contoso.com\",\"Guid\":\"244818ae-87ca-4fcd-92ec-e79e5252348a\",\"MachineAccountName\":\"WebApplication0\",\"NetBiosName\":\"CONTOSO\",\"Sid\":\"S-1-5-21-2126729477-2524075714-3094792973\"}}"
    spec:
      serviceAccountName: {{ .ServiceAccountName }}
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
